version: "3.3"
services:
  mysql:
    image: theaska18/APP_NAME:MODE
    container_name: cms_mysql_MODE         # Password untuk user biasa
    ports:
      - PORT:3306
    volumes:
      - ./mysql-data:/var/lib/mysql         # Menyimpan data MySQL ke folder lokal
    networks:
      - cms-MODE
    restart: always
networks:
  cms-MODE:
    external: true